name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  # build-macos-10-15:
  #   runs-on: macos-10.15
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: pip3 download pypylon==1.8.0
  #     - run: unzip pypylon-*.whl
  #     - run: |
  #         cd pypylon/pylon.framework/Versions
  #         # Create symlink: Current -> A/
  #         ln -s A Current
  #         cd ..
  #         # Create symlinks: Headers -> Versions/Current/Headers/ and so on
  #         ln -s Versions/Current/Headers
  #         ln -s Versions/Current/Libraries
  #         ln -s Versions/Current/Resources
  #         cd ../..
  #     - name: Setup Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #     - run: |
  #         # Build and run example
  #         export PYLONFRAMEWORKDIR=`pwd`/pypylon
  #         cargo build --example grab
  #         ln -s $PYLONFRAMEWORKDIR/pylon.framework target/debug/examples
  #         PYLON_CAMEMU=2 target/debug/examples/grab

  build-windows:
    runs-on: windows-latest
    steps:
      - run: |
          curl -O https://files.pythonhosted.org/packages/af/76/ba5b7fc37b4151a27b5c0244b6f0b37bf34ecfeac771cd49807c7ceff848/pypylon-1.8.0-cp310-cp310-macosx_10_14_universal2.whl
          unzip pypylon-1.8.0-cp310-cp310-macosx_10_14_universal2.whl
          Rename-Item pypylon/pylon.framework/Versions/A/Headers pypylon/include
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install fd-find
      - run: pip3 download pypylon==1.8.0
      - run: fd
      - run: unzip pypylon-*.whl
      - run: |
          mkdir pyplon/lib
          mkdir pyplon/lib/x64
          copy pyplon/*.dll pyplon/lib/x64
      - run: fd
      - name: build and run example
        run: |
          cargo build --example grab
          target/debug/examples/grab
        env:
          PYLON_DEV_DIR: pypylon
