name: Build

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  # build-macos-10-15:
  #   runs-on: macos-10.15
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: pip3 download pypylon==1.8.0
  #     - run: unzip pypylon-*.whl
  #     - run: |
  #         cd pypylon/pylon.framework/Versions
  #         # Create symlink: Current -> A/
  #         ln -s A Current
  #         cd ..
  #         # Create symlinks: Headers -> Versions/Current/Headers/ and so on
  #         ln -s Versions/Current/Headers
  #         ln -s Versions/Current/Libraries
  #         ln -s Versions/Current/Resources
  #         cd ../..
  #     - name: Setup Rust
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         toolchain: stable
  #     - run: |
  #         # Build and run example
  #         export PYLONFRAMEWORKDIR=`pwd`/pypylon
  #         cargo build --example grab
  #         ln -s $PYLONFRAMEWORKDIR/pylon.framework target/debug/examples
  #         PYLON_CAMEMU=2 target/debug/examples/grab

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -O https://files.pythonhosted.org/packages/af/76/ba5b7fc37b4151a27b5c0244b6f0b37bf34ecfeac771cd49807c7ceff848/pypylon-1.8.0-cp310-cp310-macosx_10_14_universal2.whl
          unzip pypylon-1.8.0-cp310-cp310-macosx_10_14_universal2.whl
          mkdir pypylon/include
          Move-Item -Path pypylon/pylon.framework/Versions/A/Headers -Destination pypylon/include/pylon
          Copy-Item -Path pypylon/include/pylon/GenICam/* -Destination pypylon/include/ -Recurse
          Copy-Item -Path pypylon/include/pylon/GenICam/Base/* -Destination pypylon/include/ -Recurse
          New-Item pypylon/include/pylon/PylonBitmapImage.h
          New-Item pypylon/include/pylon/AviWriter.h
      - run: curl -O https://files.pythonhosted.org/packages/52/39/34150ebccecff69baabb9f437b7ac784870c9ca4804a050a5b6afc59c404/pypylon-1.8.0-cp310-cp310-win_amd64.whl
      # unzip '-o' means to overwrite.
      - run: unzip -o pypylon-1.8.0-cp310-cp310-win_amd64.whl
      - run: |
          mkdir pypylon/lib
          mkdir pypylon/lib/x64
          copy pypylon/*.dll pypylon/lib/x64
          dumpbin /EXPORTS pypylon/lib/x64/GCBase_MD__v3_1_Basler_pylon.dll > pypylon/lib/x64/GCBase_MD__v3_1_Basler_pylon.exports
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build and run example
        run: |
          cargo build --example grab
          target/debug/examples/grab
        env:
          PYLON_DEV_DIR: pypylon
